name: Lint & build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies on ${{ matrix.node }}
      run: npm install --ci
    - name: Lint on ${{ matrix.node }}
      run: npm run lint
    - name: Check if project builds on ${{ matrix.node }}
      run: npm run build
